# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://veir-panda.github.io
date_format: "ordinal"
title: 熊伟的个人博客
subtitle: "打码改变人生"
description: "熊伟的个人博客"
keywords: 熊伟, 博客, Veir, veir, blog, veir-panda, 个人博客
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Veir
#organization: zkh360.com
#organization_url: http://www.zkh360.com
github_username: veir-panda
location: Chengdu, China
email: veir.xw@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /resource/
    label: 收藏

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: veir-panda/veir-panda.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: veir-panda
    repo: blog-comments
    oauth:
        client_id: 3c5d06c032c959fff683
        client_secret: 4d88fc69f8e2bc88c208e1cc4f0ed0561a146c8d
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: veir-panda
    repo: blog-comments
    clientID: 3c5d06c032c959fff683
    clientSecret: 4d88fc69f8e2bc88c208e1cc4f0ed0561a146c8d
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: true
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
